CREATE TABLE Bus (ID TEXT PRIMARY KEY NOT NULL, LABEL TEXT, LICENSE_PLATE TEXT (7));
CREATE TABLE Fermata (ID TEXT (5) PRIMARY KEY NOT NULL, CODICE, NOME TEXT, LATITUDINE REAL, LONGITUDINE REAL);
CREATE TABLE Agenzia (ID TEXT (10) PRIMARY KEY, NOME TEXT, SITO);
CREATE TABLE Percorso (ID TEXT PRIMARY KEY NOT NULL, AGENZIA_ID TEXT REFERENCES Agenzia (ID), NOME_BREVE TEXT, NOME_COMPLETO TEXT, TIPO TEXT);
CREATE TABLE Viaggio (ID PRIMARY KEY, PERCORSO_ID TEXT, SERVIZIO_ID TEXT, TESTO_DESTINAZIONE TEXT, NOME_BREVE TEXT, DIREZIONE INTEGER, ACCESSIBILE_DIVERSAMENTE_ABILI INTEGER);
CREATE TABLE FERMATA_ORARIO (FERMATA_ID TEXT, VIAGGIO_ID TEXT, ORARIO_PARTENZA TEXT, ORARIO_ARRIVO TEXT, FERMATA_SEQUENZA INTEGER, TESTO_FERMATA TEXT, SHAPE_DIST_TRAVELED INTEGER);
CREATE TABLE UTENTE (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	USERNAME TEXT(12) UNIQUE NOT NULL,
	NOME TEXT(20) NOT NULL,
	COGNOME TEXT(20) NOT NULL,
	EMAIL TEXT(50) UNIQUE NOT NULL,
	PASSWORD TEXT(20) NOT NULL
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "PREFERITI_FERMATE" (
	"UTENTE_ID"	INTEGER NOT NULL,
	"FERMATA_ID"	INTEGER NOT NULL,
	PRIMARY KEY("UTENTE_ID","FERMATA_ID")
);
